spring.application.name=w_s

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/w_s_db
spring.datasource.username=postgres
spring.datasource.password=2411

spring.jpa.hibernate.ddl-auto=update
spring.data.jdbc.dialect=postgresql
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

jwt.secret = superSecretKey1234567890superSecretKey1234567890superSecretKey1234567890 

weatherapi.key = d2796fc6cf0444cdb60201926261703
weatherapi.base-url = http://api.weatherapi.com/v1 


file.upload-dir=uploads/images/